python-028-python-projeto-spotnews/news/urls.py
from django.urls import path
from news.views import home, details, categories, form


urlpatterns = [
    path("", home, name="home-page"),
    path("news/<int:new_id>", details, name="news-details-page"),
    path("categories", categories, name="categories-form"),
    path("news", form, name="news-form")
]

python-028-python-projeto-spotnews/news_rest/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from news_rest.views.category_view import CategoryViewSet
from news_rest.views.user_view import UserViewSet
from news_rest.views.news_view import NewsViewSet

router = DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'users', UserViewSet)
router.register(r'news', NewsViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
]

python-028-python-projeto-spotnews/spotnews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls")),
    path("", include("news_rest.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

python-028-python-projeto-spotnews/news/models.py
from django.db import models
from news.validators import title_validation


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class User(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    role = models.CharField(max_length=200)
    password = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class News(models.Model):
    title = models.CharField(max_length=200, validators=[title_validation])
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ManyToManyField('Category')
    created_at = models.DateField()
    image = models.ImageField(
      upload_to="img/", null=True, blank=True
    )

    def __str__(self):
        return self.title

python-028-python-projeto-spotnews/news/forms.py
from django import forms
from news.models import News


class News_Forms(forms.ModelForm):
    class Meta:
        model = News
        fields = "__all__"


class Category_Forms(forms.Form):
    name = forms.CharField(max_length=200, label="Nome")


category_form = Category_Forms()

news_form = News_Forms()

python-028-python-projeto-spotnews/news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from news.models import News, Category, User
from news.forms import Category_Forms, News_Forms


def home(request):
    return render(request, "home.html", {"news": News.objects.all()})


def details(request, new_id):
    return render(request, "news_details.html", 
                  {"new": get_object_or_404(News, id=new_id),
                   "category": get_object_or_404(
                       News, id=new_id).categories.all()})


def categories(request):
    form = Category_Forms()
    context = {"form": form}
    if request.method == "POST":
        for _ in range(15):
            name = request.POST.get('name')
            Category.objects.create(name=name)
        return redirect("home-page")
    return render(request, "categories_form.html", context)


def form(request):
    form = News_Forms()
    if request.method == "POST":
        form = News_Forms(request.POST, request.FILES)
        if form.is_valid():
            category = form.cleaned_data.pop('categories')
            news = News.objects.create(**form.cleaned_data)
            for _ in range(15):
                news.categories.set(category)
            return redirect("home-page")

    return render(request, "news_form.html",
                  {
                      "form": form,
                      "users": User.objects.all(),
                      "categories": Category.objects.all()
                      })

python-028-python-projeto-spotnews/news_rest/views/category_view.py
from rest_framework import viewsets
from news.models import Category
from news_rest.serializers.category_serializer import CategorySerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

python-028-python-projeto-spotnews/news_rest/views/news_view.py
from rest_framework import viewsets
from news.models import News
from news_rest.serializers.news_serializer import NewsSerializer


class NewsViewSet(viewsets.ModelViewSet):
    queryset = News.objects.all()
    serializer_class = NewsSerializer

python-028-python-projeto-spotnews/news_rest/views/user_view.py
from rest_framework import viewsets
from news.models import User
from news_rest.serializers.user_serializer import UserSerializer


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

python-028-python-projeto-spotnews/news/templates/categories_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    header, main {
      border: 1px solid #ccc;
      margin: 10px;
      padding: 10px;
      background-color: #fff;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .header-nav {
      list-style: none;
      padding: 0;
      margin: 0;
      text-align: center;
    }

    .header-links li {
      display: inline;
      margin-right: 10px;
    }

    form {
      margin-top: 20px;
      text-align: center;
    }
  </style>
  <title>Formulário para Nova Categoria</title>
</head>
<body>
  <header class="header">
    <nav class="header-nav">
      <ul class="header-links">
        <li><a href="{% url 'home-page' %}">Home</a></li>
        <li><a href="{% url 'categories-form' %}">Cadastrar Categorias</a></li>
      </ul>
    </nav>
  </header>

  <main class="main-content">
    <form method="post" action="{% url 'categories-form' %}">
      {% csrf_token %}
      {{ form }}
      <button type="submit">Salvar</button>
    </form>
  </main>
</body>
</html>

python-028-python-projeto-spotnews/news/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    header {
      background-color: #333;
      color: #fff;
      padding: 10px;
      width: 100%;
      text-align: center;
    }

    .header-links {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    .header-links a {
      color: #fff;
      text-decoration: none;
      margin: 0 10px;
    }

    .news-container {
      margin: 20px;
      text-align: center;
    }

    .news-item {
      background-color: #fff;
      border: 1px solid #ccc;
      margin-bottom: 10px;
      padding: 10px;
      max-width: 600px;
    }

    .news-title {
      margin-bottom: 5px;
    }

    .news-date {
      color: #555;
    }

    .news-item img {
      max-width: 100%;
      height: auto;
    }
  </style>
  <title>Página Inicial</title>
</head>
<body>
  <header class="header">
    <ul class="header-links">
      <li><a href="{% url 'home-page' %}">Home</a></li>
    </ul>
  </header>

  <div class="news-container">
    {% for new in news %}
      <a href="{% url 'news-details-page' new.id %}" class="news-item">
        <h2 class="news-title">{{ new.title }}</h2>
        <span class="news-date">{{ new.created_at|date:"d/m/Y" }}</span>
        {% if new.image %}
          <img src="{% static new.image.url %}" alt="{{ new.title }}">
        {% endif %}
      </a>
    {% endfor %}
  </div>
</body>
</html>

python-028-python-projeto-spotnews/news/templates/news_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    header {
      background-color: #333;
      color: #fff;
      padding: 10px;
      width: 100%;
      text-align: center;
    }

    .header-links {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    .header-links a {
      color: #fff;
      text-decoration: none;
      margin: 0 10px;
    }

    .news-details-container {
      margin: 20px;
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    .news-details-content {
      background-color: #fff;
      border: 1px solid #ccc;
      padding: 20px;
      max-width: 600px;
      width: 100%;
      box-sizing: border-box;
      margin-bottom: 20px;
    }

    .news-title {
      margin-bottom: 10px;
    }

    .news-categories, .news-author, .news-date {
      display: block;
      margin-bottom: 10px;
    }

    .news-details-container img {
      max-width: 100%;
      height: auto;
      margin-bottom: 10px;
    }
  </style>
  <title>Página de Detalhes da Notícia</title>
</head>
<body>
  <header class="header">
    <ul class="header-links">
      <li><a href="{% url 'home-page' %}">Home</a></li>
    </ul>
  </header>

  <div class="news-details-container">
    <h1 class="news-title">{{ new.title }}</h1>
    <div class="news-details-content">
      <p class="news-content">{{ new.content }}</p>
      {% for categ in category %}
        <span class="news-categories">{{ categ }}</span>
      {% endfor %}
      <span class="news-author">{{ new.author }}</span>
      {% if new.image %}
        <img src="{% static new.image.url %}" alt="{{ new.title }}">
      {% endif %}
      <span class="news-date">{{ new.created_at|date:"d/m/Y" }}</span>
    </div>
  </div>
</body>
</html>

python-028-python-projeto-spotnews/news/templates/news_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    header.header {
      background-color: #333;
      color: #fff;
      padding: 10px;
      width: 100%;
      text-align: center;
    }

    .header-links {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    .header-links a {
      color: #fff;
      text-decoration: none;
      margin: 0 10px;
    }

    form {
      margin: 20px;
      max-width: 600px;
      width: 100%;
      box-sizing: border-box;
      background-color: #fff;
      padding: 20px;
      border: 1px solid #ccc;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    form label {
      display: block;
      margin-bottom: 5px;
    }

    form input,
    form textarea,
    form select,
    form button {
      width: 100%;
      padding: 10px;
      margin-bottom: 10px;
      box-sizing: border-box;
    }

    form button {
      background-color: #333;
      color: #fff;
      border: none;
      cursor: pointer;
    }

    form button:hover {
      background-color: #555;
    }
  </style>
  <title>Formulário para Nova Notícia</title>
</head>
<body>
  <header class="header">
    <ul class="header-links">
      <li><a href="{% url 'home-page' %}">Home</a></li>
      <li><a href="{% url 'categories-form' %}">Cadastrar Categorias</a></li>
      <li><a href="{% url 'news-form' %}">Cadastrar Notícias</a></li>
    </ul>
  </header>

  <form method="post" action="{% url 'news-form' %}" enctype="multipart/form-data">
    {% csrf_token %}
    
    <label for="id_title">Título</label>
    <input type="text" name="title" id="id_title">
    
    <label for="id_content">Conteúdo</label>
    <textarea name="content" id="id_content"></textarea>
    
    <label for="id_author">Autoria</label>
    <select name="author" id="id_author">
      {% for user in users %}
        <option value="{{ user.id }}">{{ user.name }}</option>
      {% endfor %}
    </select>

    <label for="id_created_at">Criado em</label>
    <input type="date" name="created_at" id="id_created_at">
    
    <label for="id_image">URL da Imagem</label>
    <input type="file" name="image" id="id_image">

    {% for category in categories %}
      <label for="id_categories_{{ category.id }}">{{ category.name }}</label>
      <input type="checkbox" name="categories" value="{{ category.id }}">
    {% endfor %}    

    <button type="submit">Salvar</button>
  </form>
</body>
</html>